### ISSUE TITLE
Possible to sort the results of the pivot table by a column?

### ISSUE THREAD

**Issue by smach** [cbailiss/pivottabler#12]
Thanks for the cool package! Sorry if I missed it in the documentation (I did try searching!), but is it possible to sort the results of a pivot table by a total column?

**Comment by cbailiss** [comment]
There are some examples at the bottom of this page:
https://cran.r-project.org/web/packages/pivottabler/vignettes/v02-datagroups.html

Example:
```
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addColumnDataGroups("PowerType")
pt$addRowDataGroups("TOC", dataSortOrder="desc")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$sortRowDataGroups(levelNumber=1, orderBy="calculation", sortOrder="desc")
pt$renderPivot()
```

Does this meet the need?

**Comment by smach** [comment]
Yes that's exactly it, thank you. Don't know how I missed that, sorry.
