### ISSUE TITLE
Is it possible to set the column heading for RowDataGroups?

### ISSUE THREAD

**Issue by rickwargo** [cbailiss/pivottabler#16]
For example, I would like to set the column caption for both TOC and the calculations in the table below.
Is this possible now?

![image](https://user-images.githubusercontent.com/430137/53414495-e4557d00-399c-11e9-8eb4-aded9be24aa4.png)

**Comment by cbailiss** [comment]
This isn't directly supported by pivottabler - however a workaround is possible by converting the pivot table to a basictabler table.  basictabler tables allow more granular table operations such as inserting/deleting rows/columns, merging/unmerging cells, etc.  Note that you will need the latest versions of both packages that are on CRAN since converting to a basictabler table was added only recently.

The following code is a bit verbose but it does the job.

For a single caption across both columns:

```
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="NumberOfTrains", caption="Number of Trains",
                     summariseExpression="n()")
pt$defineCalculation(calculationName="MaximumSpeedMPH", caption="Maximum Speed (MPH)",
                     summariseExpression="max(SchedSpeedMPH, na.rm=TRUE)")
pt$addRowCalculationGroups()
pt$evaluatePivot()
bt <- pt$asBasicTable()
cell <- bt$cells$getCell(1, 1)
cell$rawValue <- "Single Caption"
cell$formattedValue <- "Single Caption"
bt$renderTable()
```

To split the cell into two in order to have a different caption across each column:

```
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="NumberOfTrains", caption="Number of Trains",
                     summariseExpression="n()")
pt$defineCalculation(calculationName="MaximumSpeedMPH", caption="Maximum Speed (MPH)",
                     summariseExpression="max(SchedSpeedMPH, na.rm=TRUE)")
pt$addRowCalculationGroups()
pt$evaluatePivot()
bt <- pt$asBasicTable()
bt$unmergeCells(1, 1)
cell1 <- bt$cells$getCell(1, 1)
cell1$rawValue <- "Caption 1"
cell1$formattedValue <- "Caption 1"
cell2 <- bt$cells$getCell(1, 2)
cell2$visible <- TRUE
cell2$rawValue <- "Caption 2"
cell2$formattedValue <- "Caption 2"
cell2$cellType <- cell1$cellType
bt$renderTable()
```

I will leave this issue open as an enhancement request for consideration in the future.

**Comment by rickwargo** [comment]
Thank you, @cbailiss!

**Comment by rickwargo** [comment]
Hi Chris,

Thank you for the help. I had to add a few different things as I needed to reset the cell types on all the cells in the column(s).
Also, I think pivottabler uses <th> for the column header, but basictabler uses <td>. I had to change my CSS to account for this.

I ended up with the following (the bolded lines are the additions):

    bt <- pt$asBasicTable()
    bt$unmergeCells(1, 1)

    lapply(bt$getCells(columnNumbers = c(1, 2)), function(cell) cell$cellType <- "cell")
    lapply(bt$getCells(rowNumbers = c(1)), function(cell) cell$cellType <- "columnHeader")

    cell1 <- bt$cells$getCell(1, 1)
    cell1$rawValue <- "Group"
    cell1$formattedValue <- "Group"
    cell2 <- bt$cells$getCell(1, 2)
    cell2$visible <- TRUE
    cell2$rawValue <- "Stage"
    cell2$formattedValue <- "Stage"

    bt$renderTable()


Thanks again!
Best,
Rick

**Comment by cbailiss** [comment]
@rickwargo Thanks for the feedback, especially the point about the header cells ending up as td cells instead of th cells after a pivot table has been converted to a basic table.  That is unintended and feels like a bug, but I need to investigate the impact to both basictabler and pivottabler of changing that, so it will be a while before anything is changed (I am busy with other things currently).

I've raised #17 to properly describe the problem as a separate issue.  

If/when I do make any changes, I will include compatibility options to maintain the current behaviour and will describe the changes in the NEWS file as part of any future release.

**Comment by cbailiss** [comment]
@rickwargo 
Also, re:  "I had to add a few different things as I needed to reset the cell types on all the cells in the column(s)"
Was this because of a problem in the conversion to a basic table or for some other reason?

**Comment by rickwargo** [comment]
@cbailiss The CSS changes were to work-around the TD element in the header. I had to `text-align: center` the first column and It was not easy to select the first column as the merge adjusted the first cell of each repeating section. I ended up with a crazy selector:
```
table.Table tr td:nth-child(1):not([colspan]):not(.ColumnHeader), tr td[rowspan] + td {
  text-align: center;
}
```

Additionally, I copied my `th.ColumnHeader` to `td.ColumnHeader`

**Comment by cbailiss** [comment]
Wow, that's an incredible selector!
Not sure if this would help, but you can also override individual CSS declarations on a per-cell basis.
E.g. would something like the following work, which sets text alignment from row 2 to the bottom of the R in the first column?
```
bt$setStyling(2, 1, bt$rowCount, 1, declarations=list("text-align"="center"))
bt$renderTable()
```
One other thought that may or may not be relevant:  One organisation I know that uses pivottabler and basictabler manages all of their CSS definitions outside R.  Essentially, the tables are generated with CSS class names in the html, but no CSS in the R output.  The R output then goes into their web content management system which owns the definitions of the styles.  To work this they set `allowExternalStyles` on the pivottable/basictable.  There may not be an example of this in the vignettes, but I can dig one out if needed.

**Comment by rickwargo** [comment]
Thank you, @cbailiss, all helpful information. I appreciate your work on these awesome tools!

**Comment by cbailiss** [comment]
Hi @rickwargo 
There are new versions of pivottabler (v1.2.0) and basictabler (v0.3.0) now on CRAN.  
In particular, both packages now generate table header cells using the th HTML element.
The previous behaviour is still available via a compatibility setting if your code now expects/depends on td cells - see the NEWS file for details.
I will still keep this issue open as an enhancement request for setting the column headers for row data groups.

**Comment by cbailiss** [comment]
v1.3.0 released today supports setting the column headers for row data groups.  
For an example, see [http://pivottabler.org.uk/articles/v02-datagroups.html#pivot-tables-as-standard-tables-row-group-headings](http://pivottabler.org.uk/articles/v02-datagroups.html#pivot-tables-as-standard-tables-row-group-headings)
