### ISSUE TITLE
format is an R function

### ISSUE THREAD

**Issue by msgoussi** [cbailiss/pivottabler#21]
fun <- function(f, n = 1) format(round(f, n), nsmall = n, big.mark = ",")
if I would like to apply function in the format argument of defineCalculation, and I would like to control n.
i.e.
trains <- mutate(bhmtrains,
                 ArrivalDelta = difftime(ActualArrival, GbttArrival, units = "mins"),
                 ArrivalDelay = ifelse(ArrivalDelta < 0, 0, ArrivalDelta))
fun <- function(f, n = 1) format(round(f, n), nsmall = n, big.mark = ",")
pt <- PivotTable$new()
pt$addData(trains)
pt$addRowDataGroups("TOC", totalCaption = "All TOCs")
pt$defineCalculation(calculationName = "TotalTrains",
                     caption = "Total Trains", summariseExpression = "n()",
                     format = fun)
pt$defineCalculation(calculationName = "MaxArrivalDelay",
                     caption = "Max Arr. Delay", summariseExpression = "max(ArrivalDelay, na.rm = TRUE)")
pt$defineCalculation(calculationName = "MeanArrivalDelay",
                     caption = "Mean Arr. Delay", summariseExpression = "mean(ArrivalDelay, na.rm = TRUE)", 
                     format = fun(n = 2))
pt$renderPivot()

it returns error

**Comment by cbailiss** [comment]
You are receiving this error because of the way you are passing the format argument.  It looks like you are trying to specify a custom formatting function - however when doing this, only the name can be specified - not arguments as well - i.e. (n = 2) is not valid here.

Please see the under the "Formatting calculated values" heading on the following vignette for details of supported approaches to formatting:
https://cran.r-project.org/web/packages/pivottabler/vignettes/v03-calculations.html

I understand the complication - formatting non-integers in R is harder than it should be - with different formatting functionality splits between `sprintf()`, `format()`, etc.

Some examples of possibilities that do work with pivottabler:

Basic `sprintf()` style numerical formatting (but without thousands separator):

```
library(pivottabler)
library(dplyr)
trains <- mutate(bhmtrains,
                 ArrivalDelta = difftime(ActualArrival, GbttArrival, units = "mins"),
                 ArrivalDelay = ifelse(ArrivalDelta < 0, 0, ArrivalDelta))
fun <- function(f, n = 1) format(round(f, n), nsmall = n, big.mark = ",")
pt <- PivotTable$new()
pt$addData(trains)
pt$addRowDataGroups("TOC", totalCaption = "All TOCs")
pt$defineCalculation(calculationName = "TotalTrains",
                     caption = "Total Trains", summariseExpression = "n()",
                     format = "%.1f")
pt$defineCalculation(calculationName = "MaxArrivalDelay",
                     caption = "Max Arr. Delay", summariseExpression = "max(ArrivalDelay, na.rm = TRUE)")
pt$defineCalculation(calculationName = "MeanArrivalDelay",
                     caption = "Mean Arr. Delay", summariseExpression = "round(mean(ArrivalDelay, na.rm = TRUE), 2)",
                     format = "%.2f")
pt$renderPivot()
```

Specifying arguments to the `format()` function:

```
library(pivottabler)
library(dplyr)
trains <- mutate(bhmtrains,
                 ArrivalDelta = difftime(ActualArrival, GbttArrival, units = "mins"),
                 ArrivalDelay = ifelse(ArrivalDelta < 0, 0, ArrivalDelta))
fun <- function(f, n = 1) format(round(f, n), nsmall = n, big.mark = ",")
pt <- PivotTable$new()
pt$addData(trains)
pt$addRowDataGroups("TOC", totalCaption = "All TOCs")
pt$defineCalculation(calculationName = "TotalTrains",
                     caption = "Total Trains", summariseExpression = "n()",
                     format = list(nsmall = 1, big.mark = ","))
pt$defineCalculation(calculationName = "MaxArrivalDelay",
                     caption = "Max Arr. Delay", summariseExpression = "max(ArrivalDelay, na.rm = TRUE)")
pt$defineCalculation(calculationName = "MeanArrivalDelay",
                     caption = "Mean Arr. Delay", summariseExpression = "round(mean(ArrivalDelay, na.rm = TRUE), 2)",
                     format = list(nsmall = 2, big.mark = ","))
pt$renderPivot()
```

Using custom functions:

```
library(pivottabler)
library(dplyr)
trains <- mutate(bhmtrains,
                 ArrivalDelta = difftime(ActualArrival, GbttArrival, units = "mins"),
                 ArrivalDelay = ifelse(ArrivalDelta < 0, 0, ArrivalDelta))
fun1 <- function(f) format(round(f, 1), nsmall = 1, big.mark = ",")
fun2 <- function(f) format(round(f, 2), nsmall = 2, big.mark = ",")
pt <- PivotTable$new()
pt$addData(trains)
pt$addRowDataGroups("TOC", totalCaption = "All TOCs")
pt$defineCalculation(calculationName = "TotalTrains",
                     caption = "Total Trains", summariseExpression = "n()",
                     format = fun1)
pt$defineCalculation(calculationName = "MaxArrivalDelay",
                     caption = "Max Arr. Delay", summariseExpression = "max(ArrivalDelay, na.rm = TRUE)")
pt$defineCalculation(calculationName = "MeanArrivalDelay",
                     caption = "Mean Arr. Delay", summariseExpression = "mean(ArrivalDelay, na.rm = TRUE)",
                     format = fun2)
pt$renderPivot()
```

Hope that helps.

**Comment by cbailiss** [comment]
If not being able to specify arguments to the custom function is a really big problem (e.g. because you have lots and lots of variations), please let me know and I'll convert this issue to an enhancement request for the future, e.g. something like the following could be a possible enhancement:

```
pt$defineCalculation(calculationName = "MeanArrivalDelay",
                     caption = "Mean Arr. Delay", summariseExpression = "mean(ArrivalDelay, na.rm = TRUE)",
                     format = fun, fmtargs = list(n=2))
```

**Comment by msgoussi** [comment]
fmtargs = list(n=2) would be a great job for users.

**Comment by cbailiss** [comment]
Reopening issue as future enhancement request.
It will likely be a few months before I get to this due to other work.

**Comment by cbailiss** [comment]
v1.3.0 released today supports specifying arguments to custom format functions.
See the examples under the "Formatting examples with custom R function" heading on this page:  [http://pivottabler.org.uk/articles/v03-calculations.html](http://pivottabler.org.uk/articles/v03-calculations.html)
