### ISSUE TITLE
arranging pivot table column

### ISSUE THREAD

**Issue by fqlim** [cbailiss/pivottabler#25]
Hi, I would like to arrange the column according to the month.

Like, Jan Sales Qty, Feb Sales Qty, Mar Sales Qty, Apr Sales Qty......

And my coding is line by month, as below,

`pt$defineCalculation(calculationName="Jan Sales Qty", summariseExpression="sum(X1Qty)")
pt$defineCalculation(calculationName="Feb Sales Qty", summariseExpression="sum(X2Qty)")
pt$defineCalculation(calculationName="Mar Sales Qty", summariseExpression="sum(X3Qty)")
pt$defineCalculation(calculationName="Apr Sales Qty", summariseExpression="sum(X4Qty)")
pt$defineCalculation(calculationName="May Sales Qty", summariseExpression="sum(X5Qty)")
pt$defineCalculation(calculationName="Jun Sales Qty", summariseExpression="sum(X6Qty)")
pt$defineCalculation(calculationName="Jul Sales Qty", summariseExpression="sum(X7Qty)")
pt$defineCalculation(calculationName="Aug Sales Qty", summariseExpression="sum(X8Qty)")
pt$defineCalculation(calculationName="Sep Sales Qty", summariseExpression="sum(X9Qty)")
pt$defineCalculation(calculationName="Oct Sales Qty", summariseExpression="sum(X10Qty)")
pt$defineCalculation(calculationName="Nov Sales Qty", summariseExpression="sum(X10Qty)")
pt$defineCalculation(calculationName="Dec Sales Qty", summariseExpression="sum(X10Qty)")
`

But the output as below,

![image](https://user-images.githubusercontent.com/57242921/67998457-931c2c80-fc93-11e9-9e54-dc0b25c63067.png)

**Comment by cbailiss** [comment]
Thanks for reporting this.  It is definitely a bug.  I have developed a fix - which will be released soon.  I will confirm here after the fix is released.

**Comment by cbailiss** [comment]
The fix has been published to CRAN.
