### ISSUE TITLE
Support multiple pivot table layouts

### ISSUE THREAD

**Issue by cbailiss** [cbailiss/pivottabler#26]
It is helpful in some scenarios to be able to compact the row data group headings columns.
Each additional level of row data group headings currently adds another column, so the pivot table can be overly wide for some use cases.
Excel supports three different layouts that offer different ways of working with row data group headings (see attached).
One approach would be to add a layout="" parameter to the different render methods (HTML and Excel, but probably not Latex).
To avoid overly complex rendering code (and breaking the existing rendering code), it is probably worth having entirely separate rendering methods internally for the different layouts.

[PivotTableLayoutOptions.xlsx](https://github.com/cbailiss/pivottabler/files/4034085/PivotTableLayoutOptions.xlsx)

**Comment by cbailiss** [comment]
[PivotTableLayoutOptions.xlsx](https://github.com/cbailiss/pivottabler/files/4050555/PivotTableLayoutOptions.xlsx)

**Comment by cbailiss** [comment]
The above is about alternative layouts for regular pivot tables.
For these, need to be able to add in row/column group separators (i.e. e.g. for row data groups, a blank header row with a caption only is needed).

Note that the addDataGroups methods already support moving the totals to before/after set of value groups.  So supporting the above other layouts is really about adding blank rows before/after the value groups, setting the caption on the blank value groups and then not emitting the caption on the value groups.

Also, of the proposed new layouts, **Tabular** and **Outline** will be represented structurally in the pivot table.  They are generated by new parameters in the addRowColumnDataGroups methods.
**Compact** is really just a rendering option that mashes all the rowgroup columns into one column, representing the group level by the level of indentation.  So compact becomes a parameter passed to the rendering methods (getHtml(), saveHtml(), renderPivot() and writeToWorksheet()).

Therefore the proposed layout parameter isn't the best approach.

Also, more generally, it would be helpful to look at the methods / ease of building alternative layouts, irregular layouts, etc.

For example, consider the following stacked layout:

```
gender <- c("F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M")
age <- c(19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22)
grade <- c("A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E")
counts <- c(6, 16, 56, 37, 213, 14, 21, 61, 45, 191, 30, 54, 74, 82, 246, 91, 46, 29, 71, 296, 3, 6, 21, 35, 162, 14, 11, 29, 22, 204, 15, 30, 49, 75, 253, 45, 22, 30, 30, 319)

df <- data.frame(gender, age, grade, counts)

library(pivottabler)
pt <- PivotTable$new()
pt$addData(df)
pt$addColumnDataGroups("grade")
pt$rowGroup$addChildGroup(caption="Age")
pt$addRowDataGroups("age", atLevel=1)
pt$rowGroup$addChildGroup(caption="Gender")
pt$addRowDataGroups("gender", atLevel=1)
pt$defineCalculation(calculationName="GradeCounts", summariseExpression="sum(counts)")
pt$renderPivot()
```

![image](https://user-images.githubusercontent.com/11745789/72376294-9efd8380-3705-11ea-857b-8e148d2ee511.png)

In the above example, it would be easier if there was a better method for inserting a blank row (needs new styles?) and for appending/stacking different sets of data groups (atLevel kind of works, but other options are needed for more flexibility).
An easier method to append/insert blank rows (actually blank data groups) without values appearing (some kind of isEmptySpace=TRUE/FALSE property? - which addDataGroups() never expands) would be useful for both regular pivots with alternative layouts and for irregular pivots such as the above example.
Building a regular pivot with an alternative layout could then be done by specifying an additional parameter in the addRow/ColumnDataGroups() method that describes whether to add a header row with a custom caption, etc.

The data groups are actually a hierarchy, so adding/removing new rows/columns is essentially about manipulating these hierarchies.  
1) Modify the data group to support appending/inserting (via an additional parameter in addChildGroup() that specifies index as a number or before/after as a sibling data group, or NULL to append at the end as now) and removing (via a new method that removes based on a list of group indexes or list of objects).  
2) Modify addRow/ColumnDataGroups to support specifying a specific location in the pivot table by:  relatedGroup=another data group (or NULL = pivot table = as now), relativePosition=leafLevel (as now)/before/after (i.e. siblings).  This helps support irregular layouts by giving easier control about where groups are inserted.
3) Modify addRow/ColumnDataGroups to support specifying emptyFirstGroup=TRUE/caption, emptyLastGroup=TRUE/caption (to support headings, e.g. "Age", "Gender" in the above irregular layout", where these data groups have isEmptySpace=TRUE.
4) Modify addRow/ColumnDataGroups to support specifying layout=flat(default as now)/outline/outlineWithTotals, where outline renders each group with as a header with the row group caption (and IsEmptySpace=TRUE if not showing totals) and a sibling that has the filter but no caption.
5) When adding child groups, never expand a IsEmptySpace group, just add another IsEmptySpace child.
6) When generating cells, pay attention to IsEmptySpace.  Add an IsEmptySpace property to cells?
7) When rendering to Html/Excel, IsEmptySpace headers get merged and IsEmptySpace cells get merged.

**Comment by msgoussi** [comment]
I tired to understand the above, it is possible to show how to insert a an empty row between each age and gender group.

**Comment by cbailiss** [comment]
Hi @msgoussi 

Sorry for the confusion, the above comments were just thoughts of mine, not intended for others (so I've hidden the comment now).
Inserting blank rows is not fully supported currently - it is something I am in the middle of properly adding support for. For now, the following limited workaround is possible:

```
gender <- c("F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M")
age <- c(19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22)
grade <- c("A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E")
counts <- c(6, 16, 56, 37, 213, 14, 21, 61, 45, 191, 30, 54, 74, 82, 246, 91, 46, 29, 71, 296, 3, 6, 21, 35, 162, 14, 11, 29, 22, 204, 15, 30, 49, 75, 253, 45, 22, 30, 30, 319)

df <- data.frame(gender, age, grade, counts)

library(pivottabler)
pt <- PivotTable$new()
pt$addData(df)
pt$addColumnDataGroups("grade")
pt$rowGroup$addChildGroup(caption="Age", variableName="gender", values=NA)
pt$addRowDataGroups("age", atLevel=1)
pt$rowGroup$addChildGroup(caption="Gender", variableName="gender", values=NA)
pt$addRowDataGroups("gender", atLevel=1)
pt$defineCalculation(calculationName="GradeCounts", summariseExpression="sum(counts)")
pt$renderPivot()
```

![qp](https://user-images.githubusercontent.com/11745789/72805230-4751a180-3c4a-11ea-901a-aadf6acf18fa.png)

**Comment by cbailiss** [comment]
v1.3.0 released today allows new layout options.  See the "Regular Layout" and "Irregular Layout" vignettes at [http://pivottabler.org.uk/articles/](http://pivottabler.org.uk/articles/) .

@msgoussi re: "insert a an empty row between each age and gender group"
If the above answer is not what you are looking, please could you provide an example.
