### ISSUE TITLE
Is it possible to create a table without sub result?

### ISSUE THREAD

**Issue by mguller** [cbailiss/pivottabler#27]
Hi,

Thanks a lot for a great package.
In excel, there is an option "do not show sub result", when we create a pivot table. 
Is it also possible to do that with this package?

**Comment by cbailiss** [comment]
Yes, this is possible, e.g.
pt$addRowDataGroups("SchedSpeedMPH", addTotal=FALSE)

Full example on this page:
http://www.pivottabler.org.uk/articles/v01-introduction.html#extending-the-basic-pivot-table
Search for "addTotal" in this page to find the example.
