### ISSUE TITLE
rownames as columns option in $asDataFrame()

### ISSUE THREAD

**Issue by ismailmuller** [cbailiss/pivottabler#29]
It would be nice to have an option giving the possibility to put the rownames as columns when calling the `$asDataFrame()`.

I personnaly use the following

```
qpvt2 <- function(df, rows=NULL, columns=NULL, calculations=NULL, separator = "__"){
  # pivot table with rownames as separate columns
  qpvt(df, rows, columns, calculations) %>% 
  {.$asDataFrame(separator = separator)} %>% 
    tibble::rownames_to_column() %>% 
    tidyr::separate(rowname, rows, sep = separator)
}
```

But maybe the feature can be directly be built in the package...

**Comment by cbailiss** [comment]
Thanks for the suggestion - it is a interesting idea..  I will build this into a future release.

**Comment by cbailiss** [comment]
This will be submitted to CRAN in the next few days.
