### ISSUE TITLE
Error with asDataFrame() when rows = NULL

### ISSUE THREAD

**Issue by ismailmuller** [cbailiss/pivottabler#30]
I think there might be a bug when using `$asDataFrame()` on pivottable with `NULL` rows.
I don't know if it comes from actually first using `qpvt()` but here the code is below.

``` r
library(pivottabler)

X <- qpvt(iris, NULL, "Species", "mean(Sepal.Length)")
X$asDataFrame()
#> Error in grps[[c]]: attempt to select less than one element in integerOneIndex

X <- qpvt(iris, "Species", "Species", "mean(Sepal.Length)")
X$asDataFrame()
#>            setosa versicolor virginica    Total
#> setosa      5.006         NA        NA 5.006000
#> versicolor     NA      5.936        NA 5.936000
#> virginica      NA         NA     6.588 6.588000
#> Total       5.006      5.936     6.588 5.843333

X <- qpvt(iris, "Species", NULL, "mean(Sepal.Length)")
X$asDataFrame()
#>            calc000001
#> setosa       5.006000
#> versicolor   5.936000
#> virginica    6.588000
#> Total        5.843333
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

PS: thank you very much for this package. Actually the best I've used so far for pivot table in `R`

**Comment by cbailiss** [comment]
Thanks for reporting this.  Definitely a bug.
I will release a fix in 3-5 days time.

**Comment by cbailiss** [comment]
A fix for this has been created, tested and merged into the master branch.
It will be released to CRAN in a couple of days.
