### ISSUE TITLE
Delete unused aggregation levels

### ISSUE THREAD

**Issue by MarcoPortmann** [cbailiss/pivottabler#39]
I would like to display the aggregation of balance sheet items with pivottabler. I have named the smallest unit in the example code item. For some items there are intermediate aggregates, such as Group 2 for items 1 & 2 and Group3 for items 3 & 4, but for others, such as items 5 & 6, there are no such aggregates. In other words, items 5 & 6 are added directly to Group 4. For item 7 + 8 and item 9 + 10 there are intermediate aggregate, but not as many as for items 1-4.

My approach so far has been to use the same names for levels i + 1 as for i if no parent level is defined. I am searching for duplicated names and delete them. This works for item items 5 & 6. For items 7-8, I lose the lowest level. 9-10 shows an alternative approach for the same problem as in  7-8. If no alternative exists, I would use this one.

However, I'm wondering whether there is also a way to delete intermediate levels without losing the sub-items?

```
library(pivottabler)

Tab <- data.frame(Value = 1:10,
                 Level1 = paste0("Item ", 1:10),
                 Level2 = c("Group 1", "Group 1", "Group 2", "Group 2", "Item 5", "Item 6", "Item 7 + 8", "Item 7 + 8", "Item 9", "Item 10"),
                 Level3 = c("Group 3", "Group 3", "Group 3", "Group 3", "Item 5", "Item 6", "Item 7 + 8", "Item 7 + 8", "Item 9", "Item 10"),
                 Level4 = c("Group 4", "Group 4", "Group 4", "Group 4", "Item 5", "Item 6", "Item 7 + 8", "Item 7 + 8", "Item 9 + 10", "Item 9 + 10"),
                 Level5 = rep("Group 5", 10)
                 )


pt <- PivotTable$new()
pt$addData(Tab)

pt$addRowDataGroups("Level5", addTotal = F, outlineBefore = list(isEmpty = FALSE))
pt$addRowDataGroups("Level4", addTotal = F, outlineBefore = list(isEmpty = FALSE))
pt$addRowDataGroups("Level3", addTotal = F, outlineBefore = list(isEmpty = FALSE))
pt$addRowDataGroups("Level2", addTotal = F, outlineBefore = list(isEmpty = FALSE))
pt$addRowDataGroups("Level1", addTotal = F)

pt$defineCalculation(calculationName = "Sum", summariseExpression="sum(Value)")
# Table with repetition
pt$renderPivot()

# Remove repeated levels:

# Works
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level4" = "Item 5"))
Fnd[[1]]$removeGroup()
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level4" = "Item 6"))
Fnd[[1]]$removeGroup()
 
# Deletes child items:
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level2" = "Item 7 + 8"))
Fnd[[1]]$removeGroup()
 
# Alternative solution to the same problem as for Item 7 + 8: works
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level3" = "Item 9"))
Fnd[[1]]$removeGroup()
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level3" = "Item 10"))
Fnd[[1]]$removeGroup()

#pt$defineCalculation(calculationName = "Sum", summariseExpression="sum(Value)")
pt$renderPivot()
```

In the example above I've deleted Level1-4 for item 5 & 6:
In cases where I only need to delete level 1:
```
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list("Level1" = "Item 5"))
Fnd[[1]]$removeGroup()
pt$renderPivot()
```
I find that only the caption will be deleted but the row and data is still there:
![image](https://user-images.githubusercontent.com/7468121/80408578-ac5f0800-88c7-11ea-9fca-15980737576f.png)
Is it possible to remove the first level only?

**Comment by cbailiss** [comment]
Hi Marco
I'll look into this over the next couple of days.
When you say "remove the first level only", do you mean at the bottom (e.g. the blank row for item 5) and/or a parent group and not lose the children?
Would it be possible for you to mock up (e.g. in Excel or similar) the output you are looking for to help my understanding.
My initial impressions are the "blank" line for item 5 is caused by the outline layout I think.  I am not sure how easy this is to change for one specific group - I'll investigate.
The variable depth hierarchy is something I haven't considered as a usage scenario for pivottabler before, so there may be some broader (not immediate) changes that could be made to better support that kind of requirement.

**Comment by MarcoPortmann** [comment]
I think this table comes pretty close to the desired result for this use case:

![image](https://user-images.githubusercontent.com/7468121/80689858-3b3d7180-8ace-11ea-9683-05207b09a318.png)

I create the table above based on the table below using the approach for item 9+10 mentioned in the previous post by searching for child groups that have the same name as the parent groups and then deleting all child levels.

![image](https://user-images.githubusercontent.com/7468121/80690128-a8e99d80-8ace-11ea-9c9e-f3e370fe52ac.png)

- This approach works if I delete more than one level. If only the lowest hierarchical level is deleted (because only level 1 and level 2 are identical), not the whole line for level 1 is deleted, but only the caption. If I understand correctly, your question refers to this: In this use case the whole line for level 1 should be deleted, but not the parent groups (levels 2 - 5) . See comment * below.
- This approach works because I delete all sub-groups. But formally it would be more correct and visually nicer if the first level would remain in the table (for example, if "Recieved interests" is displayed on the first level, for which the values are not in bold). This requires that I can delete "Received interests" from level 2-5, but level 1 remains. 

Comment*: Interestingly, the whole line is actually deleted when I do the following:
Example  Level 1 caption <> Level 2 caption:
```
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list(Level1 = "Crop production"))
invisible(lapply(Fnd, function(x)x$removeGroup()))
```
But only the caption is deleted when I do the following:
Example  Level 1 caption == Level 2 caption:
```
Fnd <- pt$findRowDataGroups(matchMode = "simple", variableValues = list(Level1 = "Received interests"))
invisible(lapply(Fnd, function(x)x$removeGroup()))
```

I have simply filled the columns for the groups in the data.frame by filling in the child level text. Technically, one could argue that these columns should rather be NAs:

Level 8 | Level 7 | Level 6 | Level 5 | Level 4 | Level 3 | Level 2 | Level 1
-- | -- | -- | -- | -- | -- | -- | --
Net   entrepreneurial income | Net operating   surplus | <NA> | <NA> | <NA> | <NA> | Interests and   rents | Received   interests
Instead of: 

Level 8 | Level 7 | Level 6 | Level 5 | Level 4 | Level 3 | Level 2 | Level 1
-- | -- | -- | -- | -- | -- | -- | --
Net   entrepreneurial income | Net operating   surplus | Interests and rents | Received   interests | Received interests | Received interests | Received   interests | Received   interests

**Comment by cbailiss** [comment]
Thank you for the detailed reply.  Very useful.
My first thought is that removing groups is a bit painful - i.e. trying to clean up a problem, whereas it would be better to prevent the problem.
One idea - if each row in the data frame had a "MaximumDisplayLevel" column (or similar), then it might be possible for pivottabler to stop adding any groups below that level for that row in the data frame.  I need to see how easy that would be to implement - but if it is possible, would that work for you?

**Comment by cbailiss** [comment]
For example, for "Paid Rents", the "MaximumDisplayLevel" in the data frame would be set to 3.

**Comment by MarcoPortmann** [comment]
The suggestion sounds good. The same output as above could be achieved without the "create first, then delete" detour. 👍

**Comment by cbailiss** [comment]
I have spend a few hours today looking at this.  Again, it is an interesting usage scenario.
I have added a couple of capabilities to help with this:

- The ability to specify an additional filter when adding data groups (`onlyAddGroupIf`).  This only makes sense in the outline layout (as you are using).
- The ability to more easily remove empty rows.
- The ability to specify custom sort orders when building the pivot table.

Walking through an example:

```
df <- data.frame(
  Level1 = c("Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income"),
  Level2 = c("Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Interests and rents","Interests and rents","Interests and rents"),
  Level3 = c("Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Compensation of employees","Paid rent","Paid interest","Received interest"),
  Level4 = c("Net value added","Net value added","Net value added","Net value added","Net value added","Net value added","Taxes and subsidies","Taxes and subsidies",NA,NA,NA,NA),
  Level5 = c("Gross value added","Gross value added","Gross value added","Gross value added","Gross value added","Depreciation","Other taxes on production","Other subsidies (non-product specific)",NA,NA,NA,NA),
  Level6 = c("Production of the agricultural industry","Production of the agricultural industry","Production of the agricultural industry","Production of the agricultural industry","Intermediate services",NA,NA,NA,NA,NA,NA,NA),
  Level7 = c("Crop production","Livestock production","Production of agricultural services","Other production",NA,NA,NA,NA,NA,NA,NA,NA),
  MaxGroupLevel = c(7,7,7,7,6,5,5,5,3,3,3,3),
  Value = c(4210.9,4857.7,676.6,405.8,-6299,-2086.7,-145.4,2920.6,-1245,-236.5,-244.7,10.1)
)

library(pivottabler)
pt <- PivotTable$new(argumentCheckMode="balanced")
pt$addData(df)
pt$addRowDataGroups("Level1", onlyAddGroupIf="MaxGroupLevel>=1", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE))
pt$addRowDataGroups("Level2", onlyAddGroupIf="MaxGroupLevel>=2", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE),
                    dataSortOrder="custom", customSortOrder=c("Net operating surplus", "Interests and rents"))
pt$addRowDataGroups("Level3", addTotal=FALSE, onlyAddGroupIf="MaxGroupLevel>=3", outlineBefore=list(isEmpty=FALSE),
                    dataSortOrder="custom", customSortOrder=c("Factor income", "Compensation of employees",
                                                              "Paid rent", "Paid interest", "Received interest"))
pt$addRowDataGroups("Level4", onlyAddGroupIf="MaxGroupLevel>=4", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE))
pt$addRowDataGroups("Level5", onlyAddGroupIf="MaxGroupLevel>=5", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE),
                    dataSortOrder="custom", customSortOrder=c("Gross value added", "Depreciation", "Other taxes on production",
                                                              "Other subsidies (non-product specific)"))
pt$addRowDataGroups("Level6", onlyAddGroupIf="MaxGroupLevel>=6", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE),
                    dataSortOrder="custom", customSortOrder=c("Production of the agricultural industry", "Intermediate Services"))
pt$addRowDataGroups("Level7", onlyAddGroupIf="MaxGroupLevel>=7", addTotal=FALSE,
                    dataSortOrder="custom", customSortOrder=c("Crop production", "Livestock production",
                                                              "Production of agricultural services", "Other production"))
pt$defineCalculation(calculationName="Value", summariseExpression="sum(Value)")
pt$renderPivot()
```

This results in the following pivot table:

![image](https://user-images.githubusercontent.com/11745789/80871876-62e73200-8ca6-11ea-80cd-c1de6b0ac418.png)

As you can see, most of the child groups are now not added, thanks to the `onlyAddGroupIf` criteria.

However, the outline layout automatically adds a child, which causes some extra rows.  I am working on a way to prevent this, however, for now, adding the following two lines easily deals with these rows.

Removing the `pt$renderPivot()` line from the code above, and adding:

```
pt$evaluatePivot()
pt$removeEmptyRows()
pt$renderPivot()
```

This results in:

![image](https://user-images.githubusercontent.com/11745789/80871952-c2ddd880-8ca6-11ea-8854-567a09e890f0.png)

This is better, however, to my eyes, the formatting could be better.  The following additional code tidies up the formatting a bit:

```
# get all row groups (at all levels in the hierarchy)
grps1 <- pt$allRowGroups
# filter these groups to only groups with a caption and where the associated outline group was removed
# navigating outline groups is not easy currently - i will log an enhancement for this
getLeafLevelOutlineGroups <- function(x) {
  if((nchar(x$caption)>0)&&(x$doesOutlineLinkedGroupStillExist==FALSE)) return(x)
  else return(NULL)
}
grps2 <- lapply(grps1, getLeafLevelOutlineGroups)
grps3 <- grps2[lengths(grps2) != 0]
# set the styling of these groups so the text isn't bold
pt$setStyling(groups=grps3, declarations =list("font-weight"="normal"))

# find the cells corresponding to these groups
rowNumbers <- sapply(grps3, pt$findGroupRowNumbers)
cells <- pt$getCells(rowNumbers=rowNumbers)
# set the styling of these cells to be normal cells, instead of the darker outline styling
pt$setStyling(cells=cells, baseStyleName="Cell")
# draw the pivot table
pt$renderPivot()
``` 

This results in:

![image](https://user-images.githubusercontent.com/11745789/80871976-f6206780-8ca6-11ea-98bb-2d30726f6fa8.png)

To my eyes, this looks better - however it is subjective of course :-)

This code is in guthub on the development branch.  You are welcome to install it and try it.  It can be installed using something like:

`devtools::install_github("cbailiss/pivottabler", ref="development")`

**Comment by cbailiss** [comment]
I have now added a new argument `onlyAddOutlineChildGroupIf ` which controls whether child groups get added, i.e. this is a slightly more elegant solution than the one above as it removes the need to call `pt$removeEmptyRows()`.

Updated example is below.  The pivot table that is generated looks the same as the last image in my previous comment.

The "development" branch now includes this new argument, so feel free to try it.

```
df <- data.frame(
  Level1 = c("Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income","Net entrepreneurial income"),
  Level2 = c("Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Net operating surplus","Interests and rents","Interests and rents","Interests and rents"),
  Level3 = c("Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Factor income","Compensation of employees","Paid rent","Paid interest","Received interest"),
  Level4 = c("Net value added","Net value added","Net value added","Net value added","Net value added","Net value added","Taxes and subsidies","Taxes and subsidies",NA,NA,NA,NA),
  Level5 = c("Gross value added","Gross value added","Gross value added","Gross value added","Gross value added","Depreciation","Other taxes on production","Other subsidies (non-product specific)",NA,NA,NA,NA),
  Level6 = c("Production of the agricultural industry","Production of the agricultural industry","Production of the agricultural industry","Production of the agricultural industry","Intermediate services",NA,NA,NA,NA,NA,NA,NA),
  Level7 = c("Crop production","Livestock production","Production of agricultural services","Other production",NA,NA,NA,NA,NA,NA,NA,NA),
  MaxGroupLevel = c(7,7,7,7,6,5,5,5,3,3,3,3),
  Value = c(4210.9,4857.7,676.6,405.8,-6299,-2086.7,-145.4,2920.6,-1245,-236.5,-244.7,10.1)
)

library(pivottabler)
pt <- PivotTable$new(argumentCheckMode="balanced") # explicitly specifying argumentCheckMode is recommended in development versions
pt$addData(df)
pt$addRowDataGroups("Level1", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>1")
pt$addRowDataGroups("Level2", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>2",
                    dataSortOrder="custom", customSortOrder=c("Net operating surplus", "Interests and rents"))
pt$addRowDataGroups("Level3", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>3",
                    dataSortOrder="custom", customSortOrder=c("Factor income", "Compensation of employees",
                                                              "Paid rent", "Paid interest", "Received interest"))
pt$addRowDataGroups("Level4", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>4")
pt$addRowDataGroups("Level5", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>5",
                    dataSortOrder="custom", customSortOrder=c("Gross value added", "Depreciation", "Other taxes on production",
                                                              "Other subsidies (non-product specific)"))
pt$addRowDataGroups("Level6", addTotal=FALSE, outlineBefore=list(isEmpty=FALSE), onlyAddOutlineChildGroupIf="MaxGroupLevel>6",
                    dataSortOrder="custom", customSortOrder=c("Production of the agricultural industry", "Intermediate Services"))
pt$addRowDataGroups("Level7", addTotal=FALSE,
                    dataSortOrder="custom", customSortOrder=c("Crop production", "Livestock production",
                                                              "Production of agricultural services", "Other production"))
pt$defineCalculation(calculationName="Value", summariseExpression="sum(Value)")
pt$evaluatePivot()

# get all row groups (at all levels in the hierarchy)
grps1 <- pt$allRowGroups
# filter these groups to only groups with a caption and where the associated outline group was removed
# navigating outline groups is not easy currently - i will log an enhancement for this
getLeafLevelOutlineGroups <- function(x) {
  if((nchar(x$caption)>0)&&(x$outlineLinkedGroupExists==FALSE)) return(x)
  else return(NULL)
}
grps2 <- lapply(grps1, getLeafLevelOutlineGroups)
grps3 <- grps2[lengths(grps2) != 0]
# set the styling of these groups so the text isn't bold
pt$setStyling(groups=grps3, declarations =list("font-weight"="normal"))

# find the cells corresponding to these groups
rowNumbers <- sapply(grps3, pt$findGroupRowNumbers)
cells <- pt$getCells(rowNumbers=rowNumbers)
# set the styling of these cells to be normal cells, instead of the darker outline styling
pt$setStyling(cells=cells, baseStyleName="Cell")
# draw the pivot table
pt$renderPivot()
```

**Comment by MarcoPortmann** [comment]
Hi Chris,
many thanks for your development work! I will run the code from the development branch this week and give you some feedback.

**Comment by cbailiss** [comment]
Development changes are now largely complete for the next release.  I expect to release to CRAN this weekend.
Any feedback received after Friday will go into a future release (probably sometime in June).

**Comment by MarcoPortmann** [comment]
btw. I tried out a few things (code from above and calcFuncArgs) and everything seems to work fine. 👍

**Comment by cbailiss** [comment]
Released to CRAN on 11th May.
