### ISSUE TITLE
Values blank out when dealing with multiple calculation groups

### ISSUE THREAD

**Issue by meichan1128** [cbailiss/pivottabler#59]
The following example is copied from your website and modified a bit (which might not be a realistic example), I was wondering how to achieve the expected result. I found out that the values of "PowerType" items are not blank only if cg1 and cg2 is not defined. Thank you very much.

```
dt <- PivotTable$new()
dt$addData(bhmtrains)

dt$addRowDataGroups("TOC")

dt$addColumnGroup(variable=NULL, caption="PowerType")
dt$addColumnDataGroups("PowerType",addTotal = FALSE)
dt$addColumnDataGroups("Origin", fromData=FALSE, explicitListOfValues=list("ABD", "EUS"),addTotal = FALSE)

dt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
dt$defineCalculation(calculationGroupName="calcGrp2", calculationName="MaxSpeedMPH", summariseExpression="max(SchedSpeedMPH, na.rm=TRUE)")

cg1 = dt$addColumnGroup(variableName="TrainCategory", values = "Express Passenger")
cg2 = dt$addColumnGroup(variableName="TrainCategory", values = "Ordinary Passenger")

cg1$addCalculationGroups("default")
cg2$addCalculationGroups("calcGrp2")

dt$renderPivot()
```
Result
![image](https://user-images.githubusercontent.com/52668872/105636533-ca33ba80-5ea3-11eb-9316-4d33e5cf930c.png)

Expected result
![image](https://user-images.githubusercontent.com/52668872/105636626-f64f3b80-5ea3-11eb-932c-b2b8140e9f31.png)

**Comment by cbailiss** [comment]
Custom layouts like this one are more complicated than simple pivot tables.

A working version of the code is below.  One of the differences in this code is that I save the return values from the addDataGroup function.  Each of these return values is a column group.  We can then call functions on each of these column groups to specify calculations, add more child groups, etc.

```
library(pivottabler)

dt <- PivotTable$new()
dt$addData(bhmtrains)

dt$addRowDataGroups("TOC")

# save the return value as this is the column group that was added (used below)
colGrp1 <- dt$addColumnGroup(caption="PowerType")
colGrp2 <- dt$addColumnGroup(variableName="TrainCategory", values="Express Passenger")
colGrp3 <- dt$addColumnGroup(variableName="TrainCategory", values="Ordinary Passenger")

dt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
dt$defineCalculation(calculationGroupName="calcGrp2", calculationName="MaxSpeedMPH",
                     summariseExpression="max(SchedSpeedMPH, na.rm=TRUE)")

# attach the calculations to the columns groups from above
colGrp1$addCalculationGroups("default")
colGrp2$addCalculationGroups("calcGrp2")
colGrp3$addCalculationGroups("calcGrp2")

# add children to the PowerType group 
# the return value is a list containing the DMU, EMU and HST groups
colGrp1Children <- colGrp1$addDataGroups("PowerType", addTotal=FALSE)

# use lapply to add the origin groups as children to each of the DMU, EMU and HST groups
fx <- function(x) {
  x$addDataGroups("Origin", fromData=FALSE, explicitListOfValues=list("ABD", "EUS"), addTotal=FALSE)
}
invisible(lapply(colGrp1Children, fx))

# finished
dt$renderPivot()
```

![image](https://user-images.githubusercontent.com/11745789/105645883-77063b80-5e94-11eb-8b1e-b557293fe106.png)


The column headings for "Express Passenger", "Ordinary Passenger", etc are not merged across the three rows.  The pivottabler package does not support this currently.  However, if this is important, the pivot table can be converted to a basictabler table and the cells then merged.

```
# convert to basic tabler table
bt <- dt$asBasicTable()
bt$mergeCells(rFrom=1, cFrom=8, rSpan=3, cSpan=1)
bt$mergeCells(rFrom=1, cFrom=9, rSpan=3, cSpan=1)
bt$renderTable()
```

![image](https://user-images.githubusercontent.com/11745789/105646036-74581600-5e95-11eb-96b1-92c6f4c26686.png)
