### ISSUE TITLE
Remove cell 

### ISSUE THREAD

**Issue by trang-n** [cbailiss/pivottabler#62]
Hi, I'm trying to find a way to remove the empty cells that were created by the addRowDataGroups function. Can I selectively choose values to be shown? For example, I don't want to have blank values in the regions. 
Thank you.
![image](https://user-images.githubusercontent.com/47608071/112522213-bdccc080-8d73-11eb-9ebc-81d7b353b6e8.png)

**Comment by cbailiss** [comment]
It is possible to specify a list of values using the fromData and explicitListOfValues arguments.

```
# all TOC values
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains) 
pt$addColumnDataGroups("TrainCategory") 
pt$addRowDataGroups("TOC") 
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
```
![image](https://user-images.githubusercontent.com/11745789/112558313-60159400-8dc6-11eb-9d96-39217ad8b9b6.png)


```
# only two TOC values
library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains) 
pt$addColumnDataGroups("TrainCategory") 
pt$addRowDataGroups("TOC", fromData=FALSE, explicitListOfValues=list("CrossCountry", "London Midland")) 
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
```
![image](https://user-images.githubusercontent.com/11745789/112558460-bbe01d00-8dc6-11eb-9004-5325d796f6d8.png)
