### ISSUE TITLE
Export PV to pdf

### ISSUE THREAD

**Issue by trf66** [cbailiss/pivottabler#64]
Hello, 
I would like to get some tips about the export of pivot table to pdf file.
I have followed the method describe here http://www.pivottabler.org.uk/ but, an error message appears.
It refers to pdfcrop and ghostscript.

I have rode a lot of messages on forums (including https://stackoverflow.com/questions/66305776/got-knit-issue-with-r) and tryed to re install Markdown, tinytex without results.
As I don't have administrator's right to install pdfcrop and ghostscrip, i would like to get help to get an alternative solution....
(Rstudio v1.3)
As i complexe data table,ideally I would like to continue to use the packager, it would avoid me to start all over again 

Thanks

```

---
title: "Untitled"
output: pdf_document
header-includes:
  -\usepackage{multirow}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='asis', echo=FALSE, comment=""}
pt <- PivotTable$new()
pt$addData(bhmTrains)
pt$addColumnDataGroups("TrainCategory") 
pt$addRowDataGroups("TOC",  header="Spécialité",  addTotal=FALSE)
pt$defineCalculation(calculationName="TOTAL", 
                                 summariseExpression="n()")
cat(pt$getLatex(caption="test", label="xxxxx"))
```

```

I get the following message
```
Error in pt$getLatex : objet de type 'closure' non indiçable
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> cat
De plus : Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: pdfcrop, ghostscript
-> As a result, figure cropping will be disabled.
```

**Comment by cbailiss** [comment]
Sorry for the slow reply.  Unfortunately general help creating PDFs is not something I can help with.  I suggest posting your question on stackoverflow or similar.
