### ISSUE TITLE
Float renderPivot table in R Markdown

### ISSUE THREAD

**Issue by moloscripts** [cbailiss/pivottabler#66]
After Rendering the pivot table using `pt$renderPivot()`, I'd like to float it either right, left of any text in R Markdown. The result should be something similar to the screenshot attached. 

![Screen Shot 2021-06-02 at 17 27 31](https://user-images.githubusercontent.com/1729842/120498447-e4d4ed80-c3c7-11eb-9ffb-9b24bc55fefe.png)

**Comment by cbailiss** [comment]
The attached example markdown file shows how to use this.  (You need to change the file extension back to .Rmd).

Result:
