### ISSUE TITLE
outlineBefore receiving Error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by rhyschellew** [cbailiss/pivottabler#68]
The following code is receiving the error "Error in if (nchar(captionValue) > 0) captionValue <- gsub("\\{value\\}",  : 
  missing value where TRUE/FALSE needed".
It only occurs when the line "outlineBefore=TRUE" is run, otherwise I get the pivottable I expect.

`pt <- PivotTable$new()
pt$addData(staff)
pt$addColumnDataGroups("date")
pt$addColumnDataGroups("department")
pt$addRowDataGroups("level",
                    addTotal = TRUE,
                    outlineBefore=TRUE)
pt$addRowDataGroups("rank",
                    dataSortOrder = "custom",
                    customSortOrder = c("CFO", "COO", "DL","Grad", "Entry", "Misc",
                    addTotal = TRUE)
pt$defineCalculation(calculationName = 
                       "Count of people",
                     summariseExpression =
                     "paste(round((sum(declaration)/n())*100, digits = 2),
                       '%',
                     sep = '')"
                     )
pt$renderPivot()`

I'm really new to R, so if you could explain like I'm 5, that'd really help. That said, I was hoping to build on the outline to format and move the total around etc.

**Comment by cbailiss** [comment]
Are you able to share your data as that would help me understand the problem?
`write.csv(staff, "C:\\Users\\PeterSmith\\Desktop\\Data.csv", row.names=FALSE)`
You can attach here or email.  My email address can be found in the "Maintainer" field here:
https://cran.r-project.org/web/packages/pivottabler/index.html
